# Starter pipeline

trigger:
- main

pool:
  vmImage: windows-2019

variables:
  counter: $[counter('$(Build.SourceBranch)', 0)]

steps:
- task: MSBuild@1
  inputs:
    solution: Project.proj
    msbuildArguments: >
        /p:BuildNumber=$(counter)
        /p:BranchName=$(Build.SourceBranch)
